export const ArenaABI = [
  {
    name: "battleCount",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "protocolFeeBps",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "battles",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "tokenA", type: "address" },
      { name: "tokenB", type: "address" },
      { name: "pot", type: "uint256" },
      { name: "teamAPot", type: "uint256" },
      { name: "teamBPot", type: "uint256" },
      { name: "minWager", type: "uint256" },
      { name: "maxWager", type: "uint256" },
      { name: "startTime", type: "uint64" },
      { name: "endTime", type: "uint64" },
      { name: "round", type: "uint16" },
      { name: "status", type: "uint8" },
      { name: "winner", type: "uint8" },
    ],
  },
  {
    name: "hasWagered",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "getBattleWagerCount",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "battleId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "paused",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "placeWager",
    type: "function",
    stateMutability: "payable",
    inputs: [
      { name: "battleId", type: "uint256" },
      { name: "side", type: "uint8" },
    ],
    outputs: [],
  },
  {
    name: "claimWinnings",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "battleId", type: "uint256" }],
    outputs: [],
  },
  {
    name: "createBattle",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tokenA", type: "address" },
      { name: "tokenB", type: "address" },
      { name: "minWager", type: "uint256" },
      { name: "maxWager", type: "uint256" },
      { name: "startTime", type: "uint64" },
      { name: "endTime", type: "uint64" },
    ],
    outputs: [{ name: "battleId", type: "uint256" }],
  },
  {
    name: "WagerPlaced",
    type: "event",
    inputs: [
      { name: "battleId", type: "uint256", indexed: true },
      { name: "player", type: "address", indexed: true },
      { name: "side", type: "uint8", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    name: "WinningsClaimed",
    type: "event",
    inputs: [
      { name: "battleId", type: "uint256", indexed: true },
      { name: "player", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
] as const;
